# Generated by Django 5.1.4 on 2026-06-30 02:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0010_historicalvinculofuncional_aviso_previo_indenizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoESocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('S-1000', 'S-1000 — Informações do empregador'), ('S-1005', 'S-1005 — Tabela de estabelecimentos')], max_length=10)),
                ('id_evento', models.CharField(help_text='ID único do eSocial (ID + inscrição + timestamp + sequencial).', max_length=36, unique=True, verbose_name='ID do evento')),
                ('versao_layout', models.CharField(default='S_01_03_00', max_length=20)),
                ('xml', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('gerado', 'Gerado'), ('validado', 'Validado (XSD)'), ('assinado', 'Assinado'), ('enviado', 'Enviado'), ('processado', 'Processado'), ('rejeitado', 'Rejeitado')], default='gerado', max_length=15)),
                ('lote', models.CharField(blank=True, max_length=40)),
                ('retorno', models.JSONField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('orgao_emissor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_esocial', to='people.orgaoemissor')),
            ],
            options={
                'verbose_name': 'evento eSocial',
                'verbose_name_plural': 'eventos eSocial',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEventoESocial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('tipo', models.CharField(choices=[('S-1000', 'S-1000 — Informações do empregador'), ('S-1005', 'S-1005 — Tabela de estabelecimentos')], max_length=10)),
                ('id_evento', models.CharField(db_index=True, help_text='ID único do eSocial (ID + inscrição + timestamp + sequencial).', max_length=36, verbose_name='ID do evento')),
                ('versao_layout', models.CharField(default='S_01_03_00', max_length=20)),
                ('xml', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('gerado', 'Gerado'), ('validado', 'Validado (XSD)'), ('assinado', 'Assinado'), ('enviado', 'Enviado'), ('processado', 'Processado'), ('rejeitado', 'Rejeitado')], default='gerado', max_length=15)),
                ('lote', models.CharField(blank=True, max_length=40)),
                ('retorno', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orgao_emissor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.orgaoemissor')),
            ],
            options={
                'verbose_name': 'historical evento eSocial',
                'verbose_name_plural': 'historical eventos eSocial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
