# Generated by Django 5.1.4 on 2026-07-03 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0001_initial'),
        ('payroll', '0007_rubrica_cod_inc_cp_rubrica_cod_inc_cprp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoesocial',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_esocial', to='payroll.rubrica'),
        ),
        migrations.AddField(
            model_name='historicaleventoesocial',
            name='rubrica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.rubrica'),
        ),
        migrations.AlterField(
            model_name='eventoesocial',
            name='tipo',
            field=models.CharField(choices=[('S-1000', 'S-1000 — Informações do empregador'), ('S-1005', 'S-1005 — Tabela de estabelecimentos'), ('S-1010', 'S-1010 — Tabela de rubricas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaleventoesocial',
            name='tipo',
            field=models.CharField(choices=[('S-1000', 'S-1000 — Informações do empregador'), ('S-1005', 'S-1005 — Tabela de estabelecimentos'), ('S-1010', 'S-1010 — Tabela de rubricas')], max_length=10),
        ),
    ]
