# Generated by Django 5.1.4 on 2026-07-04 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0002_eventoesocial_rubrica_and_more'),
        ('people', '0010_historicalvinculofuncional_aviso_previo_indenizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo_cifrado', models.TextField(help_text='PFX cifrado (Fernet). Nunca expor.')),
                ('senha_cifrada', models.TextField(help_text='Senha do PFX cifrada (Fernet). Nunca expor.')),
                ('titular', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ do titular')),
                ('emissor', models.CharField(blank=True, max_length=200, verbose_name='Autoridade certificadora')),
                ('validade_inicio', models.DateTimeField(blank=True, null=True)),
                ('validade_fim', models.DateTimeField(blank=True, null=True)),
                ('thumbprint', models.CharField(blank=True, max_length=64, verbose_name='Impressão digital (SHA-1)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('orgao_emissor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='people.orgaoemissor')),
            ],
            options={
                'verbose_name': 'certificado digital',
                'verbose_name_plural': 'certificados digitais',
            },
        ),
    ]
