# Generated by Django 5.1.4 on 2026-07-14 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0003_certificadodigital'),
        ('payroll', '0008_lancamento_snap_incide_fgts_and_more'),
        ('people', '0010_historicalvinculofuncional_aviso_previo_indenizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoesocial',
            name='folha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_esocial', to='payroll.folha'),
        ),
        migrations.AddField(
            model_name='eventoesocial',
            name='vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_esocial', to='people.vinculofuncional'),
        ),
        migrations.AddField(
            model_name='historicaleventoesocial',
            name='folha',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.folha'),
        ),
        migrations.AddField(
            model_name='historicaleventoesocial',
            name='vinculo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.vinculofuncional'),
        ),
        migrations.AlterField(
            model_name='eventoesocial',
            name='tipo',
            field=models.CharField(choices=[('S-1000', 'S-1000 — Informações do empregador'), ('S-1005', 'S-1005 — Tabela de estabelecimentos'), ('S-1010', 'S-1010 — Tabela de rubricas'), ('S-1200', 'S-1200 — Remuneração (RGPS)'), ('S-1202', 'S-1202 — Remuneração de servidor (RPPS)'), ('S-1210', 'S-1210 — Pagamentos')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaleventoesocial',
            name='tipo',
            field=models.CharField(choices=[('S-1000', 'S-1000 — Informações do empregador'), ('S-1005', 'S-1005 — Tabela de estabelecimentos'), ('S-1010', 'S-1010 — Tabela de rubricas'), ('S-1200', 'S-1200 — Remuneração (RGPS)'), ('S-1202', 'S-1202 — Remuneração de servidor (RPPS)'), ('S-1210', 'S-1210 — Pagamentos')], max_length=10),
        ),
    ]
