# Generated by Django 5.1.4 on 2026-07-14 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esocial', '0004_eventoesocial_folha_eventoesocial_vinculo_and_more'),
        ('people', '0010_historicalvinculofuncional_aviso_previo_indenizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteESocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.IntegerField(choices=[(1, 'Eventos de tabela'), (2, 'Eventos não periódicos'), (3, 'Eventos periódicos')])),
                ('status', models.CharField(choices=[('montado', 'Montado (validado)'), ('enviado', 'Enviado'), ('processado', 'Processado'), ('erro', 'Erro')], default='montado', max_length=12)),
                ('protocolo_envio', models.CharField(blank=True, max_length=60)),
                ('xml_envio', models.TextField(blank=True)),
                ('xml_retorno', models.TextField(blank=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('orgao_emissor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_esocial', to='people.orgaoemissor')),
            ],
            options={
                'verbose_name': 'lote eSocial',
                'verbose_name_plural': 'lotes eSocial',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='eventoesocial',
            name='lote_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='esocial.loteesocial'),
        ),
        migrations.AddField(
            model_name='historicaleventoesocial',
            name='lote_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esocial.loteesocial'),
        ),
    ]
