# Generated by Django 5.1.4 on 2026-05-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_grupos_papeis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salario_minimo', 'Salário mínimo'), ('inss', 'Faixas INSS'), ('irrf', 'Faixas IRRF'), ('deducao_dependente_irrf', 'Dedução por dependente (IRRF)')], max_length=40)),
                ('vigencia_inicio', models.DateField(help_text='Primeiro dia em que a tabela vigora.')),
                ('vigencia_fim', models.DateField(blank=True, help_text='Último dia de vigência (null = continua valendo).', null=True)),
                ('valores', models.JSONField(help_text='Estrutura específica por tipo — ver TabelaLegal.')),
                ('referencia_legal', models.CharField(blank=True, help_text="Lei/Decreto/Portaria de origem (ex.: 'Lei 14.663/2023').", max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tabela legal',
                'verbose_name_plural': 'tabelas legais',
                'ordering': ['tipo', '-vigencia_inicio'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'vigencia_inicio'), name='tabela_legal_unica_por_tipo_e_vigencia')],
            },
        ),
    ]
