# Generated by Django 5.1.4 on 2026-04-27 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.DateField(help_text='Primeiro dia do mes de referencia')),
                ('tipo', models.CharField(choices=[('mensal', 'Mensal'), ('13_primeira', '13o - 1a parcela'), ('13_segunda', '13o - 2a parcela'), ('ferias', 'Ferias'), ('rescisao', 'Rescisao'), ('complementar', 'Complementar')], default='mensal', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('calculada', 'Calculada'), ('conferida', 'Conferida'), ('fechada', 'Fechada')], default='aberta', max_length=20)),
                ('total_proventos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folhas', to='core.municipio')),
            ],
            options={
                'verbose_name': 'folha',
                'verbose_name_plural': 'folhas',
                'ordering': ['-competencia'],
                'unique_together': {('municipio', 'competencia', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('provento', 'Provento'), ('desconto', 'Desconto'), ('informativa', 'Informativa')], max_length=15)),
                ('incide_inss', models.BooleanField(default=False, verbose_name='Incide INSS')),
                ('incide_irrf', models.BooleanField(default=False, verbose_name='Incide IRRF')),
                ('incide_fgts', models.BooleanField(default=False, verbose_name='Incide FGTS')),
                ('formula', models.TextField(blank=True, help_text='DSL de calculo (sera implementada no Bloco 2)', verbose_name='Formula de calculo')),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='core.municipio')),
            ],
            options={
                'verbose_name': 'rubrica',
                'verbose_name_plural': 'rubricas',
                'ordering': ['codigo'],
                'unique_together': {('municipio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('referencia', models.DecimalField(decimal_places=4, default=0, help_text='Quantidade, percentual ou dias', max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='payroll.folha')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='people.servidor')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='people.vinculofuncional')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='payroll.rubrica')),
            ],
            options={
                'verbose_name': 'lancamento',
                'verbose_name_plural': 'lancamentos',
                'ordering': ['rubrica__codigo'],
            },
        ),
    ]
