# Generated by Django 5.1.4 on 2026-05-30 15:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('people', '0009_historicalservidor_tipo_logradouro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='incide_rpps',
            field=models.BooleanField(default=False, help_text='Compõe a base da previdência municipal própria (Onda 2.4).', verbose_name='Incide RPPS'),
        ),
        migrations.CreateModel(
            name='RegimePrevidenciario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text="Nome do regime/instituto (ex.: 'IPM - Instituto de Previdência Municipal').", max_length=200)),
                ('modo_contribuicao', models.CharField(choices=[('flat', 'Alíquota única'), ('progressivo', 'Tabela progressiva (EC 103)')], default='flat', max_length=15)),
                ('aliquota_servidor', models.DecimalField(decimal_places=4, default=Decimal('0.14'), help_text="Usada no modo 'flat' (ex.: 0.14 = 14%). Ignorada no progressivo.", max_digits=6, verbose_name='Alíquota do servidor')),
                ('aliquota_patronal', models.DecimalField(decimal_places=4, default=Decimal('0.22'), help_text='Contribuição do ente (ex.: 0.22 = 22%). Exposta como ALIQ_RPPS_PATRONAL.', max_digits=6, verbose_name='Alíquota patronal')),
                ('teto', models.DecimalField(blank=True, decimal_places=2, help_text='Teto da base de contribuição (null = sem teto).', max_digits=12, null=True)),
                ('faixas', models.JSONField(blank=True, default=list, help_text='Faixas progressivas (modo \'progressivo\'): [{"ate": "1518.00", "aliquota": "0.075"}, {"ate": null, "aliquota": "0.14"}]')),
                ('regimes_aplicaveis', models.JSONField(blank=True, default=list, help_text='Regimes de vínculo cobertos pelo RPPS (valores de people.Regime). Vazio = usa o padrão (apenas efetivos/estatutários).')),
                ('vigencia_inicio', models.DateField(help_text='Primeiro dia em que esta config vigora.')),
                ('vigencia_fim', models.DateField(blank=True, help_text='Último dia de vigência (null = continua valendo).', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('orgao_emissor', models.ForeignKey(blank=True, help_text='Entidade (CNPJ) gestora do RPPS, quando aplicável.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regimes_previdenciarios', to='people.orgaoemissor')),
            ],
            options={
                'verbose_name': 'regime previdenciário (RPPS)',
                'verbose_name_plural': 'regimes previdenciários (RPPS)',
                'ordering': ['-vigencia_inicio'],
                'constraints': [models.UniqueConstraint(fields=('vigencia_inicio',), name='rpps_unico_por_vigencia_inicio')],
            },
        ),
    ]
