# Generated by Django 5.1.4 on 2026-06-05 23:51

import apps.payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_rubrica_incide_rpps_regimeprevidenciario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='tipos_folha',
            field=models.JSONField(default=apps.payroll.models._default_tipos_folha, help_text="Tipos de folha em que esta rubrica é aplicada (valores de TipoFolha). Ex.: ['mensal'] ou ['13_segunda']. — Onda 3.1.", verbose_name='Tipos de folha'),
        ),
    ]
