# Generated by Django 5.1.4 on 2026-06-08 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_rubrica_tipos_folha'),
        ('people', '0010_historicalvinculofuncional_aviso_previo_indenizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dias_gozo', models.PositiveSmallIntegerField(default=30, help_text='Dias de férias gozados (salário de férias + 1/3).')),
                ('dias_abono', models.PositiveSmallIntegerField(default=0, help_text='Dias vendidos (abono pecuniário) — até 10.')),
                ('data_inicio', models.DateField(blank=True, help_text='Início do gozo (opcional).', null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_itens', to='payroll.folha')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferias_itens', to='people.vinculofuncional')),
            ],
            options={
                'verbose_name': 'item de férias',
                'verbose_name_plural': 'itens de férias',
                'ordering': ['vinculo__servidor__nome'],
                'constraints': [models.UniqueConstraint(fields=('folha', 'vinculo'), name='ferias_item_unico_por_folha_vinculo')],
            },
        ),
    ]
