# Generated by Django 5.1.4 on 2026-06-15 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_feriasitem'),
        ('people', '0010_historicalvinculofuncional_aviso_previo_indenizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folha',
            name='tipo',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('13_primeira', '13o - 1a parcela'), ('13_segunda', '13o - 2a parcela'), ('ferias', 'Ferias'), ('rescisao', 'Rescisao'), ('licenca_premio', 'Licença-prêmio (indenização)'), ('complementar', 'Complementar')], default='mensal', max_length=20),
        ),
        migrations.CreateModel(
            name='LicencaPremioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('meses', models.PositiveSmallIntegerField(default=0, help_text='Meses de licença-prêmio indenizados.')),
                ('dias', models.PositiveSmallIntegerField(default=0, help_text='Dias adicionais indenizados (0-29).')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lp_itens', to='payroll.folha')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lp_itens', to='people.vinculofuncional')),
            ],
            options={
                'verbose_name': 'item de licença-prêmio',
                'verbose_name_plural': 'itens de licença-prêmio',
                'ordering': ['vinculo__servidor__nome'],
                'constraints': [models.UniqueConstraint(fields=('folha', 'vinculo'), name='lp_item_unico_por_folha_vinculo')],
            },
        ),
    ]
