# Generated by Django 5.1.4 on 2026-06-15 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_folha_tipo_licencapremioitem'),
        ('people', '0010_historicalvinculofuncional_aviso_previo_indenizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folha',
            name='folha_origem',
            field=models.ForeignKey(blank=True, help_text='Folha mensal de origem (apenas para folhas complementares). Rastreabilidade hoje; base do modo acumulado no futuro — ADR-0019.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complementares', to='payroll.folha'),
        ),
        migrations.CreateModel(
            name='ComplementarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor explícito do lançamento (> 0).', max_digits=12)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementar_itens', to='payroll.folha')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complementar_itens', to='payroll.rubrica')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complementar_itens', to='people.vinculofuncional')),
            ],
            options={
                'verbose_name': 'item complementar',
                'verbose_name_plural': 'itens complementares',
                'ordering': ['vinculo__servidor__nome', 'rubrica__codigo'],
                'constraints': [models.UniqueConstraint(fields=('folha', 'vinculo', 'rubrica'), name='complementar_item_unico_por_folha_vinculo_rubrica')],
            },
        ),
    ]
