# Generated by Django 5.1.4 on 2026-07-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_folha_folha_origem_complementaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='cod_inc_cp',
            field=models.CharField(blank=True, help_text='Incidência da contribuição previdenciária — RGPS/INSS (Tabela 20).', max_length=2, verbose_name='Cód. incidência CP (eSocial)'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='cod_inc_cprp',
            field=models.CharField(blank=True, help_text='Incidência da contribuição ao regime próprio (setor público).', max_length=2, verbose_name='Cód. incidência CP-RPPS (eSocial)'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='cod_inc_fgts',
            field=models.CharField(blank=True, max_length=2, verbose_name='Cód. incidência FGTS (eSocial)'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='cod_inc_irrf',
            field=models.CharField(blank=True, help_text='Incidência do imposto de renda (Tabela 21).', max_length=2, verbose_name='Cód. incidência IRRF (eSocial)'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='natureza_esocial',
            field=models.CharField(blank=True, help_text='Código da natureza da rubrica no eSocial (Tabela 3). Ex.: 1000 = salário.', max_length=4, verbose_name='Natureza eSocial (Tabela 3)'),
        ),
    ]
