# Generated by Django 5.1.4 on 2026-07-10 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_rubrica_cod_inc_cp_rubrica_cod_inc_cprp_and_more'),
        ('people', '0010_historicalvinculofuncional_aviso_previo_indenizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='snap_incide_fgts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='snap_incide_inss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='snap_incide_irrf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='snap_incide_rpps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='snap_natureza_esocial',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.CreateModel(
            name='ResumoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('total_proventos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_inss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_irrf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_fgts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_rpps', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('excluir_s1200', models.BooleanField(default=False)),
                ('excluir_s1202', models.BooleanField(default=False)),
                ('excluir_s1210', models.BooleanField(default=False)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos', to='payroll.folha')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumos_folha', to='people.servidor')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumos_folha', to='people.vinculofuncional')),
            ],
            options={
                'verbose_name': 'resumo de folha',
                'verbose_name_plural': 'resumos de folha',
                'ordering': ['vinculo__servidor__nome'],
                'constraints': [models.UniqueConstraint(fields=('folha', 'vinculo'), name='resumo_unico_por_folha_vinculo')],
            },
        ),
    ]
