# Generated by Django 5.1.4 on 2026-04-27 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('holerite', 'Holerite'), ('resumo_folha', 'Resumo da folha'), ('ficha_financeira', 'Ficha financeira'), ('informe_rendimentos', 'Informe de rendimentos'), ('esocial', 'eSocial'), ('sefip', 'SEFIP'), ('outro', 'Outro')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/%Y/%m/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='core.municipio')),
            ],
            options={
                'verbose_name': 'relatorio gerado',
                'verbose_name_plural': 'relatorios gerados',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
