# Generated by Django 5.1.4 on 2026-05-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='atribuicoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='data_criacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='data_extincao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dedicacao_exclusiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='vagas_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcargo',
            name='atribuicoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcargo',
            name='data_criacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcargo',
            name='data_extincao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcargo',
            name='dedicacao_exclusiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcargo',
            name='vagas_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalservidor',
            name='instrucao',
            field=models.CharField(blank=True, max_length=2, verbose_name='código de instrução (eSocial)'),
        ),
        migrations.AddField(
            model_name='historicalservidor',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='historicalservidor',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalservidor',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalservidor',
            name='raca',
            field=models.CharField(blank=True, max_length=1, verbose_name='raça/cor'),
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='matricula_contrato',
            field=models.CharField(blank=True, help_text='Identificador do contrato no sistema legado (TRABALHADOR.REGISTRO).', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='processo_admissao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='tipo_admissao',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='servidor',
            name='instrucao',
            field=models.CharField(blank=True, max_length=2, verbose_name='código de instrução (eSocial)'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='servidor',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servidor',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servidor',
            name='raca',
            field=models.CharField(blank=True, max_length=1, verbose_name='raça/cor'),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='matricula_contrato',
            field=models.CharField(blank=True, help_text='Identificador do contrato no sistema legado (TRABALHADOR.REGISTRO).', max_length=20),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='processo_admissao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='tipo_admissao',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
