# Generated by Django 5.1.4 on 2026-05-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_cargo_atribuicoes_cargo_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallotacao',
            name='natureza',
            field=models.CharField(choices=[('administracao', 'Administração'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('assistencia_social', 'Assistência social'), ('outros', 'Outros')], default='outros', help_text='Classificação macro: administração, saúde, educação, assistência social ou outros.', max_length=30),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='natureza',
            field=models.CharField(choices=[('administracao', 'Administração'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('assistencia_social', 'Assistência social'), ('outros', 'Outros')], default='outros', help_text='Classificação macro: administração, saúde, educação, assistência social ou outros.', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalvinculofuncional',
            name='regime',
            field=models.CharField(choices=[('estatutario', 'Efetivo (concursado)'), ('celetista', 'Celetista'), ('comissionado', 'Comissionado'), ('temporario', 'Contratado temporario'), ('eletivo', 'Eletivo'), ('estagiario', 'Estagiario')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vinculofuncional',
            name='regime',
            field=models.CharField(choices=[('estatutario', 'Efetivo (concursado)'), ('celetista', 'Celetista'), ('comissionado', 'Comissionado'), ('temporario', 'Contratado temporario'), ('eletivo', 'Eletivo'), ('estagiario', 'Estagiario')], max_length=30),
        ),
    ]
