# Generated by Django 5.1.4 on 2026-05-12 23:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_refina_classificacao_naturezas_pt2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUnidadeOrcamentaria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('codigo', models.CharField(help_text="Código no SIP (DEPDESPESA), ex.: '201013'.", max_length=10)),
                ('ano', models.PositiveIntegerField(help_text='Exercício fiscal.')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('natureza', models.CharField(choices=[('administracao', 'Administração'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('assistencia_social', 'Assistência social'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical unidade orçamentária',
                'verbose_name_plural': 'historical unidades orçamentárias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UnidadeOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text="Código no SIP (DEPDESPESA), ex.: '201013'.", max_length=10)),
                ('ano', models.PositiveIntegerField(help_text='Exercício fiscal.')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('natureza', models.CharField(choices=[('administracao', 'Administração'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('assistencia_social', 'Assistência social'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unidade orçamentária',
                'verbose_name_plural': 'unidades orçamentárias',
                'ordering': ['-ano', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='unidade_orcamentaria',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='De qual orçamento sai o empenho deste vínculo (Onda 1.4-bis).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.unidadeorcamentaria'),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='unidade_orcamentaria',
            field=models.ForeignKey(blank=True, help_text='De qual orçamento sai o empenho deste vínculo (Onda 1.4-bis).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='people.unidadeorcamentaria'),
        ),
        migrations.AddConstraint(
            model_name='unidadeorcamentaria',
            constraint=models.UniqueConstraint(fields=('codigo', 'ano'), name='unidade_unica_por_codigo_e_ano'),
        ),
    ]
