# Generated by Django 5.1.4 on 2026-05-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_historicalunidadeorcamentaria_unidadeorcamentaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunidadeorcamentaria',
            name='codigo_interno_sip',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='PK interno (UNIDADE.CODIGO) do Fiorilli SIP. É por ele que TRABALHADOR.DEPDESPESA aponta — o nome do campo no SIP é enganoso.', null=True),
        ),
        migrations.AddField(
            model_name='unidadeorcamentaria',
            name='codigo_interno_sip',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='PK interno (UNIDADE.CODIGO) do Fiorilli SIP. É por ele que TRABALHADOR.DEPDESPESA aponta — o nome do campo no SIP é enganoso.', null=True),
        ),
    ]
