# Generated by Django 5.1.4 on 2026-05-28 01:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_historicalunidadeorcamentaria_codigo_interno_sip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservidor',
            name='tipo_logradouro',
            field=models.CharField(blank=True, choices=[('rua', 'Rua'), ('avenida', 'Avenida'), ('praca', 'Praça'), ('travessa', 'Travessa'), ('rodovia', 'Rodovia'), ('estrada', 'Estrada'), ('viela', 'Viela'), ('alameda', 'Alameda'), ('largo', 'Largo'), ('outro', 'Outro')], max_length=15),
        ),
        migrations.AddField(
            model_name='servidor',
            name='tipo_logradouro',
            field=models.CharField(blank=True, choices=[('rua', 'Rua'), ('avenida', 'Avenida'), ('praca', 'Praça'), ('travessa', 'Travessa'), ('rodovia', 'Rodovia'), ('estrada', 'Estrada'), ('viela', 'Viela'), ('alameda', 'Alameda'), ('largo', 'Largo'), ('outro', 'Outro')], max_length=15),
        ),
        migrations.CreateModel(
            name='HistoricalOrgaoEmissor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('cnpj', models.CharField(db_index=True, max_length=18, verbose_name='CNPJ')),
                ('eh_principal', models.BooleanField(default=False, help_text='Marca a Prefeitura matriz. Apenas um por município.', verbose_name='É o órgão principal?')),
                ('cnae_principal', models.CharField(blank=True, help_text='Código CNAE de 7 dígitos (sem separador) — usado no S-1005.', max_length=7, verbose_name='CNAE preponderante')),
                ('tipo_logradouro', models.CharField(blank=True, choices=[('rua', 'Rua'), ('avenida', 'Avenida'), ('praca', 'Praça'), ('travessa', 'Travessa'), ('rodovia', 'Rodovia'), ('estrada', 'Estrada'), ('viela', 'Viela'), ('alameda', 'Alameda'), ('largo', 'Largo'), ('outro', 'Outro')], max_length=15)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical órgão emissor',
                'verbose_name_plural': 'historical órgãos emissores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSindicato',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(db_index=True, max_length=18, verbose_name='CNPJ')),
                ('codigo_sindical', models.CharField(blank=True, help_text='Código MTE de 9 dígitos (com ou sem separador).', max_length=20, verbose_name='Código sindical')),
                ('categoria', models.CharField(blank=True, help_text='Ex.: Servidores Públicos Municipais, Trabalhadores em Educação.', max_length=200, verbose_name='Categoria representada')),
                ('base_territorial', models.CharField(blank=True, help_text='Cidade(s) ou estado(s) onde o sindicato atua.', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sindicato',
                'verbose_name_plural': 'historical sindicatos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrgaoEmissor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('eh_principal', models.BooleanField(default=False, help_text='Marca a Prefeitura matriz. Apenas um por município.', verbose_name='É o órgão principal?')),
                ('cnae_principal', models.CharField(blank=True, help_text='Código CNAE de 7 dígitos (sem separador) — usado no S-1005.', max_length=7, verbose_name='CNAE preponderante')),
                ('tipo_logradouro', models.CharField(blank=True, choices=[('rua', 'Rua'), ('avenida', 'Avenida'), ('praca', 'Praça'), ('travessa', 'Travessa'), ('rodovia', 'Rodovia'), ('estrada', 'Estrada'), ('viela', 'Viela'), ('alameda', 'Alameda'), ('largo', 'Largo'), ('outro', 'Outro')], max_length=15)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'órgão emissor',
                'verbose_name_plural': 'órgãos emissores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='historicalunidadeorcamentaria',
            name='orgao_emissor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='CNPJ que assina os empenhos desta unidade orçamentária.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.orgaoemissor'),
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='orgao_emissor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Estabelecimento (CNPJ) ao qual o vínculo é atribuído no eSocial. Tipicamente Prefeitura, Câmara, Fundo de Saúde, FMAS, etc.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.orgaoemissor'),
        ),
        migrations.AddField(
            model_name='unidadeorcamentaria',
            name='orgao_emissor',
            field=models.ForeignKey(blank=True, help_text='CNPJ que assina os empenhos desta unidade orçamentária.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_orcamentarias', to='people.orgaoemissor'),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='orgao_emissor',
            field=models.ForeignKey(blank=True, help_text='Estabelecimento (CNPJ) ao qual o vínculo é atribuído no eSocial. Tipicamente Prefeitura, Câmara, Fundo de Saúde, FMAS, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='people.orgaoemissor'),
        ),
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('codigo_sindical', models.CharField(blank=True, help_text='Código MTE de 9 dígitos (com ou sem separador).', max_length=20, verbose_name='Código sindical')),
                ('categoria', models.CharField(blank=True, help_text='Ex.: Servidores Públicos Municipais, Trabalhadores em Educação.', max_length=200, verbose_name='Categoria representada')),
                ('base_territorial', models.CharField(blank=True, help_text='Cidade(s) ou estado(s) onde o sindicato atua.', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sindicato',
                'verbose_name_plural': 'sindicatos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='sindicato',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Sindicato representante da categoria (S-2200 — vinculo/categoria/sindical).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.sindicato'),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='sindicato',
            field=models.ForeignKey(blank=True, help_text='Sindicato representante da categoria (S-2200 — vinculo/categoria/sindical).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos', to='people.sindicato'),
        ),
    ]
