# Generated by Django 5.1.4 on 2026-06-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_historicalservidor_tipo_logradouro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='aviso_previo_indenizado',
            field=models.BooleanField(default=False, help_text='Aviso prévio indenizado (dispensa sem justa causa, celetista).'),
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='motivo_demissao',
            field=models.CharField(blank=True, choices=[('pedido_demissao', 'Pedido de demissão'), ('sem_justa_causa', 'Dispensa sem justa causa'), ('com_justa_causa', 'Dispensa com justa causa'), ('termino_contrato', 'Término de contrato'), ('aposentadoria', 'Aposentadoria'), ('falecimento', 'Falecimento'), ('exoneracao', 'Exoneração (estatutário)')], help_text='Motivo do desligamento — define as verbas da folha de rescisão.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='saldo_fgts',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo do FGTS acumulado — base da multa de 40% na rescisão.', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalvinculofuncional',
            name='tem_ferias_vencidas',
            field=models.BooleanField(default=False, help_text='Tem período aquisitivo de férias completo e não gozado.'),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='aviso_previo_indenizado',
            field=models.BooleanField(default=False, help_text='Aviso prévio indenizado (dispensa sem justa causa, celetista).'),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='motivo_demissao',
            field=models.CharField(blank=True, choices=[('pedido_demissao', 'Pedido de demissão'), ('sem_justa_causa', 'Dispensa sem justa causa'), ('com_justa_causa', 'Dispensa com justa causa'), ('termino_contrato', 'Término de contrato'), ('aposentadoria', 'Aposentadoria'), ('falecimento', 'Falecimento'), ('exoneracao', 'Exoneração (estatutário)')], help_text='Motivo do desligamento — define as verbas da folha de rescisão.', max_length=20),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='saldo_fgts',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo do FGTS acumulado — base da multa de 40% na rescisão.', max_digits=12),
        ),
        migrations.AddField(
            model_name='vinculofuncional',
            name='tem_ferias_vencidas',
            field=models.BooleanField(default=False, help_text='Tem período aquisitivo de férias completo e não gozado.'),
        ),
    ]
