# Generated by Django 5.1.4 on 2026-05-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SipImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo'), ('lotacao', 'Lotação'), ('servidor', 'Servidor'), ('vinculo', 'Vínculo Funcional'), ('dependente', 'Dependente'), ('rubrica', 'Rubrica (evento)')], max_length=20)),
                ('chave_sip', models.CharField(help_text="Identificador estável na origem (ex.: '001-PROFE' para Cargo).", max_length=120)),
                ('arminda_id', models.PositiveIntegerField(blank=True, help_text='PK do registro criado no Arminda. Null se status=erro.', null=True)),
                ('payload_sip_hash', models.CharField(blank=True, help_text='sha256 do dict bruto vindo do SIP — detecta drift na origem.', max_length=64)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('erro', 'Erro')], default='ok', max_length=10)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'registro de importação SIP',
                'verbose_name_plural': 'registros de importação SIP',
                'ordering': ['-importado_em'],
                'indexes': [models.Index(fields=['tipo', 'status'], name='imports_sip_tipo_eb0146_idx')],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'chave_sip'), name='sip_import_unico_por_tipo_e_chave')],
            },
        ),
    ]
