# Generated by Django 5.1.4 on 2026-05-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipimportrecord',
            name='tipo',
            field=models.CharField(choices=[('cargo', 'Cargo'), ('lotacao', 'Lotação'), ('unidade_orcamentaria', 'Unidade orçamentária'), ('servidor', 'Servidor'), ('vinculo', 'Vínculo Funcional'), ('dependente', 'Dependente'), ('rubrica', 'Rubrica (evento)')], max_length=20),
        ),
    ]
